name: Publish to PyPI via uv

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write   # for PyPI trusted publishing
  contents: read    # required for actions/checkout

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: Build and publish
        run: uv publish --yes
